### ISSUE TITLE
Address upmove, -128 & z-rotation cheats

### ISSUE THREAD

**Issue by Aciz** [ETrun/ETrun#197]
- Upmove:

bg_pmove.c, L2683:

```
	if (pm->cmd.upmove < 0) {
		pm->cmd.upmove = 127;
	}
```

- -128:

bg_pmove.c, L2550:

```
	if (pm->cmd.rightmove < -127) {
		pm->cmd.rightmove = -127;
	}

	if (pm->cmd.forwardmove < -127) {
		pm->cmd.forwardmove = -127;
	}
```

- Z-Rotation:

bg_pmove.c, L2063

```
	for (i = 0 ; i < 2 ; ++i) {
```
This disables client's ability to rotate z-view. There should probably also be a check for this in timerun start since teleporters are able to still rotate z-view (not sure if ETRun has any maps that do that, but just in case). `if (client->ps.viewangles[ROLL] != 0)` -> don't start timerun.

**Comment by boutetnico** [comment]
Thank your for your contribution @Aciz.

For reference:
- ET Dev `dev_MoveSpeed` sets max possible value of `upmove`/`forwardmove`/`rightmove` to -128
- ET Dev `dev_UpMove` sets `upmove = 10` while jumping.
