### ISSUE TITLE
Client crash when noclipping as a player on top of map "fw"

### ISSUE THREAD

**Issue by boutetnico** [ETrun/ETrun#59]

**Comment by boutetnico** [comment]
Was not able to reproduce with f1dd4c8c1a9234b8f987a96464a52c06630c1cb0, closing.

**Comment by boutetnico** [comment]
re-opening, as @suburbski can reproduce it.
looks like the crash happens in client code and also in `etmain` mod
![fw-crash](https://user-images.githubusercontent.com/973739/30004532-828faaf2-90d1-11e7-9872-37923899fa2e.png)

**Comment by suburbski** [comment]
Can't be fixed mod-sided, under certain (unknown) circumstances which all seem to meet on the maps "fw" and "fw-wall", during lightgrid calculation, [data](https://github.com/id-Software/Enemy-Territory/blob/master/src/renderer/tr_light.c#L247) points to an inaccessible chunk of memory, causing the memory access violation appcrash. Will be fixed for ETLegacy.
