### ISSUE TITLE
Make timeruns triggers visible

### ISSUE THREAD

**Issue by boutetnico** [ETrun/ETrun#67]
Add a cvar to enable disable it.
Start/stop and checkpoint triggers should be shown.

**Comment by JOTRainbow** [comment]
Is this not already possible in custommap scripts? 
Actually a checkpoint looks like this:
`create
		{
			origin "-18883 994 -9560"
			mins "-200 -200 -25"
			maxs "200 200 25"
			classname "trigger_multiple"
			target "check2"
			contents "1073741824"
		}
		create
		{
			origin "-18883 994 -9560"
			classname "target_checkpoint"
			targetname "check2"
			name "axis first gamma"
		}`

Isn't it right now just possible to add code like this

`		create
		{
			origin "-18883 994 -9560"
			classname "misc_gamemodel"
			mins "-90 -90 -25"
			maxs "90 90 25"
			model "models/mapobjects/timerun/CREATE_HERE_A_CHECKPOINTIMAGE.md3"
			fps "12"
			frames "25"
			start "0"
			spawnflags "2"
		}`

**Comment by boutetnico** [comment]
Closing because it's a duplicate of #23
